### ISSUE TITLE
Error: Invalid Chai property: calledTwice

### ISSUE THREAD

**Issue by maximebrugel** [defi-wonderland/smock#64]
Hello ! 

**Describe the bug**

When I run my test with smock :

```
Error: Invalid Chai property: calledTwice
      at Object.proxyGetter [as get] (node_modules/chai/lib/chai/utils/proxify.js:78:17)
      at Context.<anonymous> (test/unit/OperatorResolver.unit.ts:226:69)
```

**Reproduction steps**

Version => 
- "chai": "^4.3.4",
- "@defi-wonderland/smock": "^2.0.1",

```javascript
mixinResolver1 = await smock.fake<TestableMixinResolver>("TestableMixinResolver");

(...)

expect(mixinResolver1.rebuildCache).to.have.been.calledTwice;
```

Thank you in advance !

**Comment by smartcontracts** [comment]
Looking into this now!

**Comment by 0xGorilla** [comment]
Did you use the smock chai matchers?

Remember to add at the top of the file:
``` typescript
import { smock } from '@defi-wonderland/smock';
chai.use(smock.matchers);
```

**Comment by maximebrugel** [comment]
I forgot the `chai.use(smock.matchers)` 😇😇😇

Thank you !!!!
